### ISSUE TITLE
Cannot Build With FFmpeg Support

### ISSUE THREAD

**Issue by KumaTea** [pytorch/vision#3188]
### Cannot Build With FFmpeg Support

Hi.

While trying to build `torchvision` from source, I've seen this output:

```
+ python3 setup.py build
Building wheel torchvision-0.8.2
PNG found: True
libpng version: 1.6.37
Building torchvision with PNG image support
libpng include path: /usr/include/libpng16
Running build on conda-build: False
Running build on conda: False
JPEG found: True
Building torchvision with JPEG image support
FFmpeg found: False
running build
running build_py
creating build

(omitted)
```

It showed that **`FFmpeg found: False`**. I tried `apt install ffmpeg` and built again, it still showed FFmpeg not found.

Then I tried:

```shell
apt update
apt install ffmpeg \
    libavformat-dev libavcodec-dev libavdevice-dev \
    libavutil-dev libswscale-dev libavresample-dev libavfilter-dev
# deps of python package av
pip3 install ffmpeg av
```

But it showed `FFmpeg found: False` once again.

I could not find any instructions in [README](../blob/master/README.rst) about installing `ffmpeg` dependencies for building `torchvision` yet, so how could I do that, or where could I find it?

Thanks.

cc @bjuncek

**Comment by andfoy** [comment]
Hi @KumaTea, could you please check if the `ffmpeg` command is available?

**Comment by KumaTea** [comment]
> Hi @KumaTea, could you please check if the `ffmpeg` command is available?

Hi, I just checked and it is available.

**Install deps**

```
root@9e6bf2c705fc:~# uname -a
Linux 9e6bf2c705fc 5.9.14-sunxi64 #20.11.3 SMP Fri Dec 11 20:34:34 CET 2020 aarch64 aarch64 aarch64 GNU/Linux

root@9e6bf2c705fc:~# apt update
root@9e6bf2c705fc:~# apt install ffmpeg libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev libswscale-dev libavresample-dev libavfilter-dev python3-pkgconfig
root@9e6bf2c705fc:~# pip install ffmpeg av
root@9e6bf2c705fc:~# pip install torch -f https://torch.maku.ml/whl/stable.html
```

**Check ffmpeg**

```
root@9e6bf2c705fc:~# apt list --installed | grep ffmpeg

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

ffmpeg/focal-updates,focal-security,now 7:4.2.4-1ubuntu0.1 arm64 [installed]

root@9e6bf2c705fc:~# ffmpeg -version
ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers
built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/aarch64-linux-gnu --incdir=/usr/include/aarch64-linux-gnu --arch=arm64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
libavutil      56. 31.100 / 56. 31.100
libavcodec     58. 54.100 / 58. 54.100
libavformat    58. 29.100 / 58. 29.100
libavdevice    58.  8.100 / 58.  8.100
libavfilter     7. 57.100 /  7. 57.100
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  5.100 /  5.  5.100
libswresample   3.  5.100 /  3.  5.100
libpostproc    55.  5.100 / 55.  5.100
```

**Build**

```
root@9e6bf2c705fc:~# git clone https://github.com/pytorch/vision
root@9e6bf2c705fc:~# cd vision
root@9e6bf2c705fc:~/vision# VER="0.8.2"
root@9e6bf2c705fc:~/vision# export BUILD_VERSION="$VER"
root@9e6bf2c705fc:~/vision# git checkout "v$VER"
root@9e6bf2c705fc:~/vision# export MAX_JOBS=1
root@9e6bf2c705fc:~/vision# python3 setup.py build
Building wheel torchvision-0.8.2
PNG found: False
Running build on conda-build: False
Running build on conda: False
JPEG found: False
FFmpeg found: False
running build
running build_py
creating build
creating build/lib.linux-aarch64-3.8
creating build/lib.linux-aarch64-3.8/torchvision
copying torchvision/extension.py -> build/lib.linux-aarch64-3.8/torchvision

...
```

---

I don't know if the architecture `aarch64` or the virtualization env `docker` has any effect on this...

**Comment by andfoy** [comment]
It seems that setup.py is unable to find ffmpeg in the PATH, is it possible that the PATH is being modified in some way?

**Comment by KumaTea** [comment]
> It seems that setup.py is unable to find ffmpeg in the PATH, is it possible that the PATH is being modified in some way?

Probably not.

I ran **`echo $PATH`** right after the initialization of docker container, and after installing dependencies, and the output are both **`/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`**.

`which ffmpeg` outputs `/usr/bin/ffmpeg`.

---

I also tried to install `ffmpeg` and other dependencies, like `jpeg` and `libpng`, using [miniforge](https://github.com/conda-forge/miniforge), which might be more recommended for building. 

In this case, `which ffmpeg` shows `/root/miniforge3/bin/ffmpeg`, but `setup.py` still could not detect it, while `conda` is detected:

```
(base) root@8546b919cb25:~/pytorch/vision# python setup.py build
Building wheel torchvision-0.8.2
PNG found: True
libpng version: 1.6.37
Building torchvision with PNG image support
libpng include path: /root/miniforge3/include/libpng16
Running build on conda-build: False
Running build on conda: True
JPEG found: True
Building torchvision with JPEG image support
FFmpeg found: False
running build
running build_py
creating build
creating build/lib.linux-aarch64-3.8
creating build/lib.linux-aarch64-3.8/torchvision
```

**Comment by andfoy** [comment]
Could you please check in a Python interpreter the output of `distutils.spawn.find_executable('ffmpeg')`?

**Comment by KumaTea** [comment]
> Could you please check in a Python interpreter the output of `distutils.spawn.find_executable('ffmpeg')`?

Hi, here's the output:

```
root@01bda82eae37:~# python3 -c "import distutils.spawn; print(distutils.spawn.find_executable('ffmpeg'))"
None


# install deps


root@01bda82eae37:~# ffmpeg -version
ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers
built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/aarch64-linux-gnu --incdir=/usr/include/aarch64-linux-gnu --arch=arm64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
libavutil      56. 31.100 / 56. 31.100
libavcodec     58. 54.100 / 58. 54.100
libavformat    58. 29.100 / 58. 29.100
libavdevice    58.  8.100 / 58.  8.100
libavfilter     7. 57.100 /  7. 57.100
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  5.100 /  5.  5.100
libswresample   3.  5.100 /  3.  5.100
libpostproc    55.  5.100 / 55.  5.100

root@01bda82eae37:~/vision# which ffmpeg
/usr/bin/ffmpeg
root@01bda82eae37:~# python3 -c "import distutils.spawn; print(distutils.spawn.find_executable('ffmpeg'))"
/usr/bin/ffmpeg


# clone torchvision, set environment and build


root@01bda82eae37:~/vision# python3 setup.py build
Building wheel torchvision-0.8.2
PNG found: True
libpng version: 1.6.37
Building torchvision with PNG image support
libpng include path: /usr/include/libpng16
Running build on conda-build: False
Running build on conda: False
JPEG found: True
Building torchvision with JPEG image support
FFmpeg found: False
running build
running build_py
creating build
creating build/lib.linux-aarch64-3.8
creating build/lib.linux-aarch64-3.8/torchvision
copying torchvision/extension.py -> build/lib.linux-aarch64-3.8/torchvision

...
```

Looks like that `distutils` can also find `ffmpeg`.

---

I just ran the exact same commands on a `x86_64` docker container. The results are also same.

```
...


root@d9916b29461b:~/vision# python3 setup.py build
Building wheel torchvision-0.8.2
PNG found: True
libpng version: 1.6.37
Building torchvision with PNG image support
libpng include path: /usr/include/libpng16
Running build on conda-build: False
Running build on conda: False
JPEG found: True
Building torchvision with JPEG image support
FFmpeg found: False
running build
running build_py
creating build
creating build/lib.linux-x86_64-3.8
creating build/lib.linux-x86_64-3.8/torchvision
copying torchvision/utils.py -> build/lib.linux-x86_64-3.8/torchvision

...
```

**Comment by andfoy** [comment]
> None

It seems that `distutils.spawn.find_executable` is not finding ffmpeg

**Comment by andfoy** [comment]
Could you please check if `shutil.which('ffmpeg')` works?

**Comment by KumaTea** [comment]
> > None
> 
> It seems that `distutils.spawn.find_executable` is not finding ffmpeg

Actually it did... the command was executed twice, once before installing dependencies and once after.

```
root@01bda82eae37:~# which ffmpeg
/usr/bin/ffmpeg
root@01bda82eae37:~# python3 -c "import distutils.spawn; print(distutils.spawn.find_executable('ffmpeg'))"
/usr/bin/ffmpeg
```

> Could you please check if `shutil.which('ffmpeg')` works?

It doesn't work:

```
root@01bda82eae37:~# python3 -c "import shutil;shutil.which('ffmpeg')"
root@01bda82eae37:~#
```

**Comment by aweits** [comment]
The latest commit on 0.8.2 in setup.py looks to have disabled ffmpeg?
```diff
-    has_ffmpeg = ffmpeg_exe is not None
+    # Disable ffmpeg by default
+    no_ffmpeg = os.environ.get("NO_FFMPEG", True)
+    has_ffmpeg = ffmpeg_exe is not None and not no_ffmpeg

```
If there some strange way to set no_ffmpeg to False, I'm missing what that is...

**Comment by AdeelH** [comment]
I ran into this today too. It should either 
- be documented that the user should set `NO_FFMPEG=` 
- or the absence of `NO_FFMPEG` should be taken to mean that ffmpeg should be used if found, which makes a lot more sense to me:

```diff
    ffmpeg_exe = distutils.spawn.find_executable('ffmpeg')
-   # Disable ffmpeg by default
-   no_ffmpeg = os.environ.get("NO_FFMPEG", True)
+   no_ffmpeg = os.environ.get("NO_FFMPEG", False)
    has_ffmpeg = ffmpeg_exe is not None and not no_ffmpeg
    print("FFmpeg found: {}".format(has_ffmpeg))
```

**Comment by bjuncek** [comment]
Yes, this is fixed on the master. If all are ok I'll close this issue for now, and document installation process better.

**Comment by KumaTea** [comment]
Just to mention: `apt install ffmpeg` is not enough for building with FFMPEG support, both PyTorch and Torchvision, it will fail with `Headers missing` errors.

You may want to manually install (`make`) [from source](http://ffmpeg.org/releases). Check [this post](https://stackoverflow.com/a/47024694/10714490) for instructions.

**Comment by JohannesZahn** [comment]
In the Readme it says that ffmpeg can be installed with conda. If I do so and then install tochvision from sources with `python setup.py install` I still get:
FFmpeg found: False
