### ISSUE TITLE
Missed RandomResizedCrop()

### ISSUE THREAD

**Issue by icharlest** [pytorch/vision#352]
When I ran AlexNet example, I get this problem

transforms.RandomResizedCrop(224),
AttributeError: module 'torchvision.transforms' has no attribute 'RandomResizedCrop'

I find the RandomResizedCrop class in source code

**Comment by icharlest** [comment]
Fixed, I just need build vision package from source

**Comment by alykhantejani** [comment]
@icharlest we will be releasing the latest version (`0.2.0`) on conda etc soon

**Comment by SaynaEbrahimi** [comment]
I installed from source as well but the issue remains the same. Any suggestions?

**Comment by CharlesxrWu** [comment]
@SaynaEbrahimi u can try to replace the transform.py file with the correct file in the torch vision package. That's what I do, it can work.

**Comment by SaynaEbrahimi** [comment]
@CharlesxrWu Thanks for your quick reply! I checked out the latest version and installed with `python setup.py install`. Doesn't it have the correct transform.py file?

**Comment by SaynaEbrahimi** [comment]
@CharlesxrWu Thanks for the hint! I was able to fix it by manually placing the [transforms.py](https://github.com/pytorch/vision/tree/080b95437186c99d0b664fd69f18773e1c2a7d8f/torchvision/transforms) in my current folder.

**Comment by muzi-8** [comment]
@CharlesxrWu
I faced the same problem.
my pytorch is installed by offline. so how i to change the transforms.py? or Any suggestions?
Thanks!

**Comment by CharlesxrWu** [comment]
@muzi-8 
You can find where is your transforms.py file now. Download the right copy of transforms.py from Github, then replace the old one with the new one. It can work.

**Comment by muzi-8** [comment]
@CharlesxrWu 
Thanks for your detailed reply. It has solved my problem.
