### ISSUE TITLE
NameError: name 'sympy' is not defined

### ISSUE THREAD

**Issue by datumbox** [pytorch/vision#7034]
### 🐛 Describe the bug

It seems the latest core introduced a new dependency on `sympy` but it's not automatically installed. The issue [appears](https://app.circleci.com/pipelines/github/pytorch/vision/22318/workflows/f36c513d-8e2b-484e-92bf-efc35fb5f78a/jobs/1797505) on `cmake_macos_cpu `:
```
+++ python -c 'import torch; print(torch.__file__)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/distiller/miniconda3/lib/python3.9/site-packages/torch/__init__.py", line 1232, in <module>
    from . import _meta_registrations
  File "/Users/distiller/miniconda3/lib/python3.9/site-packages/torch/_meta_registrations.py", line 7, in <module>
    from torch._decomp import _add_op_to_registry, global_decomposition_table, meta_table
  File "/Users/distiller/miniconda3/lib/python3.9/site-packages/torch/_decomp/__init__.py", line 168, in <module>
    import torch._decomp.decompositions
  File "/Users/distiller/miniconda3/lib/python3.9/site-packages/torch/_decomp/decompositions.py", line 10, in <module>
    import torch._prims as prims
  File "/Users/distiller/miniconda3/lib/python3.9/site-packages/torch/_prims/__init__.py", line 34, in <module>
    from torch.fx.experimental.symbolic_shapes import sym_float
  File "/Users/distiller/miniconda3/lib/python3.9/site-packages/torch/fx/experimental/symbolic_shapes.py", line 443, in <module>
    class Symbol(sympy.Dummy):
NameError: name 'sympy' is not defined
```

### Versions

Latest main

**Comment by pmeier** [comment]
Fixed in pytorch/pytorch#90704.

**Comment by xuyingzhongguo** [comment]
I still have this problem. Any advice? Thanks!

**Comment by ClioCJS** [comment]
I have sympy installed and I'm still getting this error trying to run StableDiffusion.

**Comment by pmeier** [comment]
@ClioCJS please open a new issue and make sure you fill out the form so we can see your full env.

**Comment by Quasimondo** [comment]
I had also encountered this error after upgrading to pytorch 2.0.1 - after some digging around it turned out that sympy was already installed but it failed to initialize since it required mpmath.

I could fix it with:
`pip install mpmath --upgrade`

**Comment by darshandevelopes** [comment]
I could fix it with:
`pip install sympy --upgrade`

My PyTorch version : `2.0.1`

**Comment by its-subhash** [comment]
can you please tell me if you solved this error

**Comment by its-subhash** [comment]
@ClaireCJS  please tell me you solved this error

**Comment by ClaireCJS** [comment]
> @ClaireCJS please tell me you solved this error

I have no recollection of whether I did or not. Probably not. I moved on. After I spend hours on instructions that fail, I deem something untenable and find something else to do.

**Comment by yangdeai** [comment]
> > > @ClaireCJS please tell me you solved this error
> > 
> > 
> > I have no recollection of whether I did or not. Probably not. I moved on. After I spend hours on instructions that fail, I deem something untenable and find something else to do.
> > I stopped bothering to try to generate StableDiffusion images locally. The environments and accompanying instructions just aren't stable enough to actually be reliable enough to waste my time on.
> > If someone wants to point me to a standalone version with EXE binaries that just works (and can still be used at the command line), I'd probably use that. But STableDiffusion in python is a mess.
> > So many other projects install just fine. not this one.
> 
> > > @ClaireCJS please tell me you solved this error
> > 
> > 
> > I have no recollection of whether I did or not. Probably not. I moved on. After I spend hours on instructions that fail, I deem something untenable and find something else to do.
> > I stopped bothering to try to generate StableDiffusion images locally. The environments and accompanying instructions just aren't stable enough to actually be reliable enough to waste my time on.
> > If someone wants to point me to a standalone version with EXE binaries that just works (and can still be used at the command line), I'd probably use that. But STableDiffusion in python is a mess.
> > So many other projects install just fine. not this one.
> 
> No Prob... I solved it just now...thank you for replying.

Hi, how? I tried the advices they listed,but still fail.
